# This file was generated by GoReleaser. DO NOT EDIT.
cask "repocache" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "6440a0d2ce852e95e9570c46c3ac208c0ac2f94975a2dfce6444306ef579977f"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80142d568478a468388c613c034d73df7bda7c0a5aa4631360cd3824c46f6930"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1121f87601930c737e8291721f4064580f39511bf087c32298a93129171525d"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86ad1f9c4e6578907a6cf0a59a6f72b0c06c90fb424e412c151fdea21babf8d7"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repocache"
  desc "Read-only mirror of git repos for terminal coding agents"
  homepage "https://github.com/AndrewHannigan/repocache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repocache"

  # No zap stanza required

end
