# This file was generated by GoReleaser. DO NOT EDIT.
cask "repocache" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "1e5780cd34b72ea6beed7fdc5474b9c47d53b90f6352b2c8239bfa912029927a"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "83a60f58058bf0ce217685d98774b5c1d9ca1b3686d3f0389b6c6289ad480a31"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "882aba5ba278428e8284cb4b3e60c5a70052a381014f146264a7cf4c7fd0d5a5"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c9ffe9b237c1f472ee50b1fe1cf292ab6650d05b4e0ccee1926ddcdca7dfae7"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repocache"
  desc "Read-only mirror of git repos for terminal coding agents"
  homepage "https://github.com/AndrewHannigan/repocache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repocache"

  # No zap stanza required

end
