# This file was generated by GoReleaser. DO NOT EDIT.
cask "repocache" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "8f61574cbabedf9e007b3978ed99a7fa85b27385e27506714f2955bf1de5c60c"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0fa01c2f0c5dfdedd1b030d5d23dc2dbd815c4874cdd8716ad23a8127303799"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5667f345ec145dc91fb64c9dd10369bd5a81c0c5cd01e7b52c6d168ca7589632"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "feefd049a33e5895e1b3a0af1fbeedf1451dc2941cfcd78d612ef6b98febc252"
      url "https://github.com/AndrewHannigan/repocache/releases/download/v#{version}/repocache_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repocache"
  desc "Read-only mirror of git repos for terminal coding agents"
  homepage "https://github.com/AndrewHannigan/repocache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repocache"

  # No zap stanza required

end
