# This file was generated by GoReleaser. DO NOT EDIT.
cask "shed" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "249962e73ac25b0bb8bfd7e87620032b603b8a761203e882b29e0839a0cdff51"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "840b691e167dcec76f8517ec943662389e796aaf19ec294980d6af99d73427af"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f8b4c08e2ea3ffba433587bcfa273defb92bd6a3ac312748182fb47bc2b1213"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45f25cce9958ae9035d05a8173947ddb0e0632c75df0f9659282924560b31456"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shed"
  desc "Read-only store of git repos for terminal coding agents"
  homepage "https://github.com/AndrewHannigan/shed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shed"

  # No zap stanza required

  caveats <<~EOS
    Run this once to set up shed and wire it into your coding agents:

      shed init

    It detects your agents (Claude Code, Cursor, ...) and asks before
    editing any of their config. Interactive and idempotent — safe to re-run.
  EOS
end
