# This file was generated by GoReleaser. DO NOT EDIT.
cask "shed" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "d4527e87ee8760b6461aa66af76406f1530d152757fd9e39d8b0a25644a8fa43"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "796bced191f61ecf0d212137c2168d5d38ed76355feaf389647357af16b0362b"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d27a35e65cb0147ff0c0dba052a6dd841e76add7a23ffa60b3582379a9a7b3f"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e965276d8ff78cb2cd682ec1bad4b526645e107bba494e0fc479b3b67d7f4f1a"
      url "https://github.com/AndrewHannigan/shed/releases/download/v#{version}/shed_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shed"
  desc "Read-only mirror of git repos for terminal coding agents"
  homepage "https://github.com/AndrewHannigan/shed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shed"

  # No zap stanza required

  caveats <<~EOS
    Run this once to set up shed and wire it into your coding agents:

      shed init

    It detects your agents (Claude Code, Codex, Cursor, ...) and asks before
    editing any of their config. Interactive and idempotent — safe to re-run.
  EOS
end
